name: Generate PDF

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: pandoc/latex

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build PDF
        run: make pdf

      - name: Archive PDF
        uses: actions/upload-artifact@v2
        with:
          name: generated-pdf
          path: build/output.pdf

