name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: pandoc/latex

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Archive PDF
      uses: actions/upload-artifact@v2
      with:
        name: pdf-resume
        path: build/resume.pdf

