name: Convert Markdown to PDF

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Install LaTeX dependencies
      run: sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra context texworks

    - name: Convert Markdown to PDF
      run: |
        make pdf

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: resume.pdf
        path: resume.pdf

